### ISSUE TITLE
请教运行build_subs.py出错

### ISSUE THREAD

**Issue by plmxs2017** [hamsolo474/VideoSubFinder_ocr_path#2]
Traceback (most recent call last):
  File "build_subs.py", line 63, in gather_subs_tp
    if result['text'] == '': raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_subs.py", line 182, in <module>
    write_subs(subname, build_subs(sort_subs(gather_subs_tp(path,
  File "build_subs.py", line 74, in gather_subs_tp
    print('Did not run on: ', i)
NameError: name 'i' is not defined

**Comment by hamsolo474** [comment]
What were you running this on? can you give me some context on this error?

**Comment by hamsolo474** [comment]
我刚刚修改了
