### ISSUE TITLE
$PATH

### ISSUE THREAD

**Issue by Alqua** [hamsolo474/VideoSubFinder_ocr_path#3]
I'm having different kind of issues on windows and in a linux vm. On windows, I think it is a $path problem, where in the code can I specify tesseract path?
On linux: 
Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/chi_sim.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory. Failed loading language \'chi_sim\' Tesseract couldn\'t load any languages! Could not initialize tesseract.') 

Also, I think PIL is deprecated now, is it? install should be set to Pillow

**Comment by Alqua** [comment]
ok I could make it function in windows but it makes an error:

  File ".\build_subs.py", line 65, in gather_subs_tp
    if result['text'] == '': raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\build_subs.py", line 184, in <module>
    write_subs(subname, build_subs(sort_subs(gather_subs_tp(path,
  File ".\build_subs.py", line 76, in gather_subs_tp
    print('Did not run on: ', i)
NameError: name 'i' is not defined

Does this mean it did not detect anything?

**Comment by Alqua** [comment]
Sorry for spamming, I ran it from the RGBimages folder and it generated pretty good result. Somehow, the cleaning from videoSubFinder was too much.
